#*********************************************************************/
#  CI Pipeline - .NET + API Integration Tests                        */
#                                                                    */
# Purpose   : Build and run all unit + integration tests             */
# Trigger   : Push / Pull Request                                    */
# Runtime   : Ubuntu latest                                          */
#*********************************************************************/

name: .NET Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build C++ Library
        working-directory: CaseConversionAPI/CppLib
        run: |
            mkdir -p build
            cd build
            cmake ..
            cmake --build . --config Release

      - name: Verify native library exists
        run: |
            find CaseConversionAPI/CppLib -name "*.dylib" -o -name "*.so" -o -name "*.dll"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # test folder
      - name: Restore tests
        working-directory: CaseConversionAPI/tests/DotNetTests
        run: dotnet restore

      - name: Build tests
        working-directory: CaseConversionAPI/tests/DotNetTests
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        working-directory: CaseConversionAPI/tests/DotNetTests
        run: dotnet test --no-build --configuration Release --verbosity normal